function r = basisFunctionSet_square(x, y, type, der_order)
% Evaluate the P1/P2 basis set on the reference square.

switch type
    case 201
        r = [basisFunction_square(x(:), y(:), type, 1, der_order), ...
             basisFunction_square(x(:), y(:), type, 2, der_order), ...
             basisFunction_square(x(:), y(:), type, 3, der_order)];
    case 202
        r = [basisFunction_square(x(:), y(:), type, 1, der_order), ...
             basisFunction_square(x(:), y(:), type, 2, der_order), ...
             basisFunction_square(x(:), y(:), type, 3, der_order), ...
             basisFunction_square(x(:), y(:), type, 4, der_order), ...
             basisFunction_square(x(:), y(:), type, 5, der_order), ...
             basisFunction_square(x(:), y(:), type, 6, der_order)];
    otherwise
        error('Only P1/P2 basis types 201 and 202 are supported')
end

end